import io

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, black
from reportlab.pdfgen import canvas

from app.schemas import InvoicePdfRequest

router = APIRouter(prefix="/pdf", tags=["pdf"])

PRIMARY = HexColor("#00B368")  # slightly darker than the app's neon green — prints better on white


@router.post("/invoice")
def invoice_pdf(payload: InvoicePdfRequest):
    """
    Generates a branded, print-ready invoice PDF server-side. This is the
    alternative to the frontend's browser-print flow — use this endpoint
    when you want a consistent PDF regardless of the customer's browser, or
    to email/store invoices without a person clicking "print" at all.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Header
    c.setFillColor(black)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(20 * mm, height - 25 * mm, payload.business_name)

    c.setFillColor(PRIMARY)
    c.setFont("Helvetica-Bold", 12)
    c.drawRightString(width - 20 * mm, height - 20 * mm, payload.invoice_number)
    c.setFillColor(black)
    c.setFont("Helvetica", 9)

    c.line(20 * mm, height - 30 * mm, width - 20 * mm, height - 30 * mm)

    # Billed to
    y = height - 42 * mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(20 * mm, y, "Billed To")
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y - 6 * mm, payload.customer_name)
    if payload.customer_phone:
        c.drawString(20 * mm, y - 12 * mm, payload.customer_phone)
    if payload.customer_address:
        c.drawString(20 * mm, y - 18 * mm, payload.customer_address)

    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(width - 20 * mm, y, "Garment")
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 20 * mm, y - 6 * mm, payload.dress_name)

    # Line item table
    table_top = y - 32 * mm
    c.setFillColor(HexColor("#F3F4F6"))
    c.rect(20 * mm, table_top - 8 * mm, width - 40 * mm, 8 * mm, fill=True, stroke=False)
    c.setFillColor(black)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(22 * mm, table_top - 5.5 * mm, "Description")
    c.drawRightString(width - 22 * mm, table_top - 5.5 * mm, "Amount")

    row_y = table_top - 16 * mm
    c.setFont("Helvetica", 10)
    c.drawString(22 * mm, row_y, f"{payload.dress_name} — stitching charge")
    c.drawRightString(width - 22 * mm, row_y, f"Rs. {payload.subtotal:,.2f}")

    if payload.advance_paid > 0:
        row_y -= 8 * mm
        c.setFillColor(HexColor("#6B7280"))
        c.drawString(22 * mm, row_y, "Advance paid")
        c.drawRightString(width - 22 * mm, row_y, f"- Rs. {payload.advance_paid:,.2f}")
        c.setFillColor(black)

    c.line(20 * mm, row_y - 6 * mm, width - 20 * mm, row_y - 6 * mm)

    # Totals
    totals_y = row_y - 16 * mm
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 60 * mm, totals_y, "Subtotal")
    c.drawRightString(width - 22 * mm, totals_y, f"Rs. {payload.subtotal:,.2f}")

    totals_y -= 6 * mm
    c.drawRightString(width - 60 * mm, totals_y, f"Tax ({payload.tax_percent}%)")
    c.drawRightString(width - 22 * mm, totals_y, f"Rs. {payload.tax_amount:,.2f}")

    totals_y -= 8 * mm
    c.setStrokeColor(PRIMARY)
    c.line(width - 65 * mm, totals_y + 3 * mm, width - 20 * mm, totals_y + 3 * mm)
    c.setFillColor(PRIMARY)
    c.setFont("Helvetica-Bold", 13)
    c.drawRightString(width - 60 * mm, totals_y - 3 * mm, "Total")
    c.drawRightString(width - 22 * mm, totals_y - 3 * mm, f"Rs. {payload.total:,.2f}")

    # Notes
    if payload.notes:
        c.setFillColor(HexColor("#6B7280"))
        c.setFont("Helvetica", 8)
        c.drawString(20 * mm, 25 * mm, payload.notes[:120])

    c.setFillColor(HexColor("#9CA3AF"))
    c.setFont("Helvetica", 7)
    c.drawCentredString(width / 2, 12 * mm, "Generated by Neyora — Smart AI Tailoring Assistant")

    c.showPage()
    c.save()
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{payload.invoice_number}.pdf"'},
    )
